#!/bin/bash

VERSION=`grep -w SMC_TOOLS_RELEASE Makefile | head -1 | awk '{print($3)}'`;
LEVEL=`git log --pretty=format:'%h' -n 1`;

# Consistency check: Do we have an entry in the History section...?
if [ `grep -A 20 "Release History:" README.smctools | grep "$VERSION" | wc -l` -eq 0 ]; then
	echo "Error: 'README.smctools' is missing an entry for version '$VERSION' in 'Release History' ";
	exit 4;
fi

# Consistency check: git branch
sref=`git symbolic-ref HEAD 2>/dev/null`;
if [ "${sref}" != "refs/heads/master" ]; then
	echo;
	echo "WARNING: Building package on non-master branch.";
	echo "         Packages for publication MUST be built on the master branch!";
	echo;
fi

if [ -e smc-tools.$VERSION.tar.gz ]; then
	echo "Removing old package...";
	rm smc-tools.$VERSION.tar.gz;
fi
echo "Building smc-tools $VERSION";
build_dir=tmp/smc-tools-$VERSION;
if [ ! -e tmp ]; then
	mkdir tmp;
fi
if [ -e $build_dir ]; then
	rm -rf $build_dir;
fi
mkdir $build_dir;
sed -e "s/=SMC LEVEL=/$LEVEL/" smctools_common.h > $build_dir/smctools_common.h
cp smc.h $build_dir
cp smc_diag.h $build_dir;
cp smc_pnet.c $build_dir;
cp smcss.c $build_dir;
cp ld_pre_smc.c $build_dir;
cp Makefile $build_dir;
sed -e '/^smc-tools.spec:/,+5d' Makefile > $build_dir/Makefile;
cp LICENSE $build_dir;
cp README.smctools $build_dir;
cp af_smc.7 $build_dir;
cp smcss.8 $build_dir;
cp smc_pnet.8 $build_dir;
cp smc_run.in $build_dir;
cp smc_run.8 $build_dir;

cd tmp;
tar -zcvf ../smc-tools-$VERSION.tar.gz smc-tools-$VERSION | sed 's/^/   /';
if [ $? -eq 0 ]; then
	echo "Package smc-tools-$VERSION.tar.gz build successful";
else
	echo "Package smc-tools-$VERSION.tar.gz build failed";
fi
cd ..;
rm -rf tmp;

exit 0;
