.\" smc-device.8
.\"
.\"
.\" Copyright IBM Corp. 2020
.\" Author(s):  Guvenc Gulce <guvenc@linux.ibm.com>
.\" ----------------------------------------------------------------------
.\"
.TH SMC-DEVICE 8 "June 2020" "smc-tools" "Linux Programmer's Manual"

.SH NAME
smc-device \- Print information about SMC devices
.SH "SYNOPSIS"
.sp
.ad l
.in +8
.ti -8
.B smc
.RI "[ " OPTIONS " ]"
.B device
.RI " { " COMMAND " | "
.BR help " }"
.sp

.ti -8
.BR "smc device" 
.RI "[" 
.B "show"
.RI "] ["  
.B "all" 
.RI "] [ "  
.B type
.IR TYPE " ] [ " 
.B  netdev
.IR NETDEV " ] [ "
.B  ibdev
.IR IBDEV " ]

.ti -8
.IR TYPE " := [ "
.BR smcr " | "
.BR smcd " ]"

.SH "DESCRIPTION"
The
.B smc device
command displays SMC devices and their properties. Devices can be 
listed for SMC-R and SMC-D. The command operates with SMC-R type 
per default on all command levels.

.SS smc device show - look at the device properties

.TP
.B all  (default)
Show all the devices.

.TP
.BI type " TYPE"
List only the devices of the given type.

.TP
.BI netdev " NETDEV"
List only the device with the given network device name.

.TP
.BI ibdev " IBDEV"
List only the device ports with the given RoCE (InfiniBand) device name.

.SH OUTPUT

.SS "Net-Dev"
Network device name.
.SS "IB-Dev"
RoCE (InfiniBand) device name.
.SS "IB-P"
InfiniBand port of the RoCE device.
.SS "IB-State"
State of the RoCE device port.
.TP
.I
INACTIVE
The RoCE device port is inactive.
.TP
.I
ACTIVE
The RoCE device port is active.
.SS "Type"
Type of the underlying PCI device.
.TP
.I
RoCE_Express
Underlying used device is RoCE Express.
.TP
.I
RoCE_Express2
Underlying used device is RoCE Express 2.
.TP
.I
RoCE_Express3
Underlying used device is RoCE Express 3.
.TP
.I
ISM
Underlying used device is ISM.
.SS "Crit"
Show whether the device is critical i.e. without failover possibility.
.TP
.I
Yes
In case of SMC-R, there is at least one linkgroup running on the
device with state "SINGLE" or locally "ASYMMETRIC" which
means the linkgroups do not have any fail-over device in case of
a failure.
In case of SMC-D, there is at least one linkgroup running on the 
ISM device.
.TP
.I
No
In case of SMC-R, there is no linkgroup running on the device with 
state "SINGLE" or locally "ASYMMETRIC" which means the linkgroup(s) 
have a fallback device in case of a failure.
In case of SMC-D, there is no linkgroup running on the ISM device.
.SS "FID"
Functional ID of the PCI device.
.SS "PCI-ID"
ID of the PCI device.
.SS "PCHID"
Physical channel ID of the PCI device.
.SS "#Links"
Number of links(SMC-R)/linkgroups(SMC-D) on the device.
.SS "PNET-ID"
PNET-ID of the device. "*" means PNET-ID is set by the user. 

.SH "EXAMPLES"
.br
1. Show all devices of the type smcd:
.br

\fB# smc device show all type smcd\fP
.br

2. Show all devices of the type smcr:
.br

\fB# smc devices show all type smcr\fP
.br

3. Shows all devices with RoCE (InfiniBand) device name "mlx4_0":
.br

\fB# smc device show ibdev mlx4_0\fP
.br

4. Shows all devices with network device name "eth0":
.br

\fB# smc device show netdev eth0\fP
.br

.SH SEE ALSO
.br
.BR smcd (8),
.BR smcr (8)
