#!/bin/bash

# Copyright IBM Corp. 2018

PRINT=1;
ENABLE=2;
DISABLE=3;


function usage() {
	echo;
	echo "Usage: smc_rnics [ OPTIONS ]";
	echo;
	echo "List all available RNICs ";
	echo;
	echo "   -h, --help           this message";
	echo "   -e, --enable <FID>   enable the specified FID";
	echo "   -d, --disable <FID>  disable the specified FID";
	echo "   -r, --rawids         display 'type' as raw vendor/device IDs";
	echo;
}

function print_rnic() {
	if [ $header -eq 0 ]; then
		printf "FID         Power  PCI ID        PCHID   Type           Port  PNET ID           Interface\n";
		echo '--------------------------------------------------------------------------------------------';
		header=1;
	fi
	printf "%-10s  %-5s  %-12s  %-6s  %-14s %-4s  %-16s  %s\n" "$fid" "$power" "$addr" "$pchid" "$dev_type" "$port" "$pnet" "$int";
}

if [ "`uname -m`" != "s390x" ] && [ "`uname -m`" != "s390" ]; then
	printf "Error: s390/s390x supported only\n" >&2;
	exit 1;
fi

args=`getopt -u -o hre:d: -l enable:,disable:,help -- $*`;
[ $? -ne 0 ] && exit 1;
set -- $args;
action="print";
rawIDs=0;
while [ $# -gt 0 ]; do
	case $1 in
	"-e" | "--enable" )
		action="enable";
		fid=$2;
		shift;;
	"-d" | "--disable" )
		action="disable";
		fid=$2;
		shift;;
	"-h" | "--help" )
		usage;
		exit 0;;
	"-r" | "--rawids" )
		rawIDs=1;;
	"--" ) ;;
	* ) usage && exit 2;
	esac
	shift;
done

if [ "$action" != "print" ]; then
	[ "${fid:0:2}" == "0x" ] && fid=${fid:2};
	if [ ! -d /sys/bus/pci/slots/$fid ]; then
		echo "Error: FID 0x$fid does not exist" >&2;
		exit 4;
	fi
	power=`cat /sys/bus/pci/slots/$fid/power 2>/dev/null`;
	val=0;
	[ "$action" == "enable" ] && val=1;
	if [ $power -eq $val ]; then
		echo "Error: FID $fid is already ${action}d" >&2;
		exit 5;
	fi
	echo $val  > /sys/bus/pci/slots/$fid/power 2>/dev/null;
	if [ $? -ne 0 ]; then
		echo "Error: Failed to $action FID 0x$fid" >&2;
		exit 6;
	fi
	exit 0;
fi

header=0;
# iterate over slots, as powered-off devices won't show elsewhere
for fid in `ls -1 /sys/bus/pci/slots`; do
	cd /sys/bus/pci/slots/$fid;
	fid="0x$fid";
	power=`cat power`;
	interfaces="";
	port="";
	addr="";
	int="";
	if [ $power -eq 0 ]; then
		# device not yet hotplugged
		dev_type="";
		pchid="";
		pnet="";
		print_rnic;
		continue;
	fi
	# device is hotplugged - locate card
	for card in `ls -1 /sys/bus/pci/devices`; do
		cd /sys/bus/pci/devices/$card;
		if [ "`cat function_id`" == "$fid" ]; then
			addr=$card;
			break;
		fi
	done
	if [ "$addr" == "" ]; then
		echo "Error: No matching card found for FID $fid" >&2;
		continue;
	fi
	cd /sys/bus/pci/devices/$addr;
	id=`cat device`;
	vend=`cat vendor`;
	dev_type="$vend/$id";
	if [ $rawIDs -eq 0 ]; then
		case "$vend" in
		"0x1014" ) # IBM
			case "$id" in
			"0x04ed") dev_type="ISM";
				  port="n/a";;
			"0x044b") continue;;		# zEDC
			esac;;
		"0x15b3" ) # Mellanox
			case "$id" in
			"0x1003" | \
			"0x1004") dev_type="RoCE Express";;
			"0x1016") dev_type="RoCE Express2";;
			esac;;
		esac
	fi
	pchid="`cat pchid`";
	pnet="`cat util_string | tr -d '\000' | iconv -f IBM-1047 -t ASCII`";
	if [ -d net ]; then
		interfaces="`ls -1 net`";
	fi
	# one card can have multiple interfaces (one per port)
	if [ "$interfaces" != "" ]; then
		pnetids="$pnet";
		for int in $interfaces; do
			cd /sys/bus/pci/devices/$addr/net/$int;
			if [ -e dev_port ]; then
				port=`cat dev_port`;
				(( idx=16*$port+1 ))
				(( end=$idx+15 ))
				pnet=`echo "$pnetids" | cut -c $idx-$end`;
			fi
			print_rnic;
		done
		continue;
	fi
	print_rnic;
done

exit 0;
