.\" Copyright IBM Corp. 2021

.TH SMC_CHK 8 "January 2021" "smc-tools" "Linux Programmer's Manual"


.SH NAME
smc_chk \- SMC support diagnostics


.SH SYNOPSIS
.nf
.BI "smc_chk [OPTIONS] -C " IP
.BI "smc_chk [OPTIONS] -S"
.BI "smc_chk -i "INTERFACE

.SH DESCRIPTION
Use
.B -C/--connect
to obtain diagnostic information about the SMC support of a service that runs at a
given
.IR IP
address.
Otherwise, you can use
.B -S/--server
to start a server before connecting with
.IR -C .
Use
.B -i/--pnetid
to print the PNET ID of a specified
.IR INTERFACE .


.SH OPTIONS
.TP
.BI "\-C, \-\-connect " IP
Test SMC-D and SMC-R connectivity to
.IR IP .
Use option
.B -p/--port
to specify a
.IR PORT .
.I IP
can specify any service, including remote services.
By default,
.I IP
is assumed be in IPv4 format.
Specify
.B -6/--IPv6
if
.I IP
is an address in IPv6 format.
.TP
.BR "\-d, \-\-debug "
Show debug messages.
.TP
.BR "\-h, \-\-help"
Display a brief
.B smc_chk
usage information.
.TP
.BI "\-i, \-\-pnetid " INTERFACE
Print the PNET ID of interface
.I INTERFACE
and exit.
.TP
.BI "\-p, \-\-port " PORT
Use port
.I PORT
for any live tests. If
.I PORT
is already in use, the next free port is used.
.TP
.BR "\-S, \-\-server"
Start a server for manual tests. Use option
.B -p/--port
to specify a port.
.TP
.BR "\-v, \-\-version"
Display version information.
.TP
.BR "\-6, \-\-ipv6"
.I IP
address provided is in IPv6 format.


.SH Examples
.SS "Check whether a z/OS instance running at 192.168.37.1 is enabled for\
SMC using the 3270 console service running on port 23"
smc_chk -C 192.168.37.1 -p 23

.SS "Print PNET ID of interface eth0"
smc_chk -i eth0

.SS "Start server on port 45901 (or the next successive free port) for smc_chk -C to connect to"
smc_chk -S -p 45901


.SH RETURN CODES
On success,
.B smc_chk
returns 0.
If an error occurs, a return code other than 0 is returned.
.P


.SH SEE ALSO
.BR af_smc (7),
.BR smc_pnet (8),
.BR smc_run (8),
.BR smcd (8),
.BR smcr (8),
.BR smcss (8)
