.\" smcss.8
.\"
.\"
.\" Copyright IBM Corp. 2017, 2018
.\" Author(s):  Ursula Braun <ubraun@linux.ibm.com>
.\" ----------------------------------------------------------------------
.\"

.TH SMCSS 8 "June 2018" "smc-tools" "Linux Programmer's Manual"

.SH NAME
smcss \- print information about the AF_SMC sockets and link groups

.SH SYNOPSIS

.B smcss
.RB [ \-\-debug | \-d ]
.RB [ \-\-smcd | \-D ]
.RB [ \-\-wide | \-W ]
.P
.B smcss
.RB { \-\-all | -a }
.RB [ \-\-debug | \-d ]
.RB [ \-\-smcd | \-D ]
.RB [ \-\-wide | \-W ]
.P
.B smcss
.RB [ \-\-debug | \-d ]
.RB [ \-\-smcr | \-R ]
.RB [ \-\-wide | \-W ]
.P
.B smcss
.RB { \-\-all | -a }
.RB [ \-\-debug | \-d ]
.RB [ \-\-smcr | \-R ]
.RB [ \-\-wide | \-W ]
.P
.B smcss
.RB { \-\-listening | \-l }
.RB [ \-\-wide | \-W ]
.P
.B smcss
.RB { \-\-version | \-v }
.P
.B smcss
.RB { \-\-help | \-h }

.SH DESCRIPTION

.B smcss
prints information about the Linux AF_SMC sockets and link groups.
The type of information printed is controlled by the first argument, as follows:
.TP
.BR (none)
.br
displays a list of connecting, closing, or connected SMC sockets with basic
information.

.TP
.BR "\-a, \-\-all"
displays all types of SMC sockets: listening, opening, closing, and connected.

.TP
.BR "\-l, \-\-listening"
shows listening sockets only. These are omitted by default.

.SH OPTIONS

.TP
.BR "\-d, \-\-debug"
displays additional debug information, such as shutdown state.

.TP
.BR "\-D, \-\-smcd
displays additional SMC-D specific information. Shows SMC-D sockets only.

.TP
.BR "\-h, \-\-help"
displays usage information.

.TP
.BR "\-R, \-\-smcr
displays additional SMC-R specific information. Shows SMC-R sockets only.

.TP
.BR "\-v, \-\-version"
displays program version.

.TP
.BR "\-W, \-\-wide"
do not truncate IP addresses.

.SH OUTPUT

.SS "State"
The state of the socket.
The state can be one of these values:
.TP
.I
INIT
The SMC socket is being initialized. It is not connected nor
listening yet.
.TP
.I
CLOSED
The SMC socket is closed. It is not connected nor listening
anymore.
.TP
.I
LISTEN
The SMC socket is a listening socket, waiting for incoming connection requests.
.TP
.I
ACTIVE
The SMC socket has an established connection.
In this state, the TCP connection is fully established,
rendezvous processing has been completed, and SMC peers
can exchange data via RDMA.
.TP
.I
PEERCLW1
No further data will be sent to the peer.
.TP
.I
PEERCLW2
No further data will be sent to or received from the peer.
.TP
.I
APPLCLW1
No further data will be received from the peer.
.TP
.I
APPLCLW2
No further data will be received from or sent to the peer.
.TP
.I
APPLFINCLW
The peer has closed the socket.
.TP
.I
PEERFINCLW
The socket is closed locally.
.TP
.I
PEERABORTW
The socket was abnormally closed locally.
.TP
.I
PROCESSABORT
The peer has closed the socket abnormally.
.SS "UID"
User ID of the SMC socket.
.SS "Inode"
Inode attribute of the socket.
.SS "Local Address"
Address and port number of the local end of the SMC socket. 
The displayed address is truncated when it ends with '..'.
.BR "-W, --wide"
can be used to display addresses untruncated.
.SS "Peer Address"
Address and port number of the remote end of the socket.
Analogous to "Local Address".
.SS "Intf"
When the socket is explicitly bound with setsockopt option SO_BINDTODEVICE then
Intf shows the interface number of the Ethernet device to which the socket is bound.
.SS "Mode"
.TP
.I
SMCD
The SMC socket uses SMC-D for data exchange.
.TP
.I
SMCR
The SMC socket uses SMC-R for data exchange.
.TP
.I
TCP
The SMC socket uses the TCP protocol for data exchange, because an SMC connection 
could not be established.
.TP
In case of an error during connection setup, respective error codes will be displayed in the format <local>/<remote>.
.HP
Linux error codes:
.TP 13
.I
0x01010000
Out of memory
.TP 13
.I
0x02010000
Timeout while waiting for confirm link message over RDMA device
.TP
.I
0x02020000
Timeout while waiting for RDMA device to be added
.TP
.I
0x03000000
Configuration error
.TP
.I
0x03010000
Peer does not support SMC
.TP
.I
0x03020000
Connection uses IPsec
.TP
.I
0x03030000
No SMC devices found (R and D)
.TP
.I
0x03030001
No ISM device for SMC-D found
.TP
.I
0x03030002
No RDMA device for SMC-R found
.TP
.I
0x03030003
Hardware has no ISMv2 support
.TP
.I
0x03030004
Peer sent no SMCv2 extension
.TP
.I
0x03030005
Peer sent no SMC-Dv2 extension
.TP
.I
0x03030006
Peer sent no ISMv2 SEID
.TP
.I
0x03030007
No SMC-Dv2 device found, but required
.TP
.I
0x03040000
SMC modes mismatch (R or D)
.TP
.I
0x03050000
Peer has eyecatcher in RMBE
.TP
.I
0x03060000
Fastopen sockopt not supported
.TP
.I
0x03070000
IP prefix / subnet mismatch
.TP
.I
0x03080000
Error retrieving VLAN ID of IP device
.TP
.I
0x03090000
Error while registering VLAN ID on ISM device
.TP
.I
0x030a0000
No active SMC-R link in link group
.TP
.I
0x030b0000
SMC-R link from server not found
.TP
.I
0x030c0000
SMC version mismatch
.TP
.I
.I
0x030d0000
SMC-D connection limit reached
.TP
.I
0x04000000
Synchronization error
.TP
.I
0x05000000
Peer declined during handshake
.TP
.I
0x09990000
Internal error
.TP
.I
0x09990001
rtoken handling failed
.TP
.I
0x09990002
RDMA link failed
.TP
.I
0x09990003
RMB registration failed

.SS "ShutD"
.TP
.I
<->
The SMC socket has not been shut down.
.TP
.I
R->
The SMC socket is shut down one-way and cannot receive data.
.TP
.I
<-W
The SMC socket is shut down one-way and cannot send data.
.TP
.I
R-W
The SMC socket is shut down in both ways and cannot receive or send data.
.SS "Token"
Unique ID of the SMC socket connection.
.SS "Sndbuf"
Size of the to-be-sent window of the SMC socket connection.
.SS "Rcvbuf"
Size of the receiving window of the SMC socket connection (filled by peer).
.SS "Peerbuf"
Size of the peer receiving window of the SMC socket connection (to fill
during RDMA-transfer).
.SS "rxprod-Cursor"
Describes the current cursor location of the "Rcvbuf" for data to be received
from the peer.
.SS "rxcons-Cursor"
Describes the current cursor location of the "Peerbuf" for data sent to peer
and confirmed by the peer.
.SS "rxFlags"
SMC socket connection flags set by and received from the peer.
.SS "txprod-Cursor"
Describes the current cursor location of the "Peerbuf" for data sent to peer.
.SS "txcons-Cursor"
Describes the current cursor location of the "Rcvbuf" for data received from
the peer and confirmed to the peer.
.SS "txFlags"
SMC socket connection flags set locally and sent to the peer.
.SS "txprep-Cursor"
Describes the current cursor location of the "Sndbuf" for data to be sent.
The data is to be moved to the "Peerbuf".
.SS "txsent-Cursor"
Describes the current cursor location of the "Sndbuf" for data sent.
The data was moved to the "Peerbuf".
.SS "txfin-Cursor"
Describes the current cursor location of the "Sndbuf" for data sent and
send completion confirmed.
The data was moved to the "Peerbuf" and completion was confirmed.
.SS "Role"
.TP
.I
CLNT
The link group of the SMC socket is used for client connections.
.TP
.I
SERV
The link group of the SMC socket is used for server connections.
.SS "IB-Device"
Name of the RoCE device used by the link group to which the SMC socket belongs.
.SS "Port"
Port of the RoCE device used by the link group to which the SMC socket belongs.
.SS "Linkid"
Unique link ID of the link within the link group to which the SMC socket belongs.
.SS "GID"
Gid of the RoCE port used by the link group to which the SMC socket belongs.
.SS "Peer-GID"
Gid of the Foreign RoCE port used by the link group to which the SMC socket belongs.
.SS "VLAN"
tbd.
.SH RETURN CODES
Successful
.IR smcss
commands return 0 and display the
requested socket state table or link group information.
If an error occurs,
.IR smcss
writes a message to stderr and completes with a return code other than 0.
.P
.SH SEE ALSO
.BR af_smc (7),
.BR smc_chk (8)
.BR smc_rnics (8),
.BR smc_run (8),
.BR smc_pnet (8),
.BR smcd (8),
.BR smcr (8)

